### ISSUE TITLE
ReferenceError: is_sdk is not defined

### ISSUE THREAD

**Issue by Telokis** [numbereself/caracAL#3]
```
Error: Uncaught [ReferenceError: is_sdk is not defined]
    at reportException (/home/telokis/dev/git/caracAL/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at Timeout.task [as _onTimeout] (/home/telokis/dev/git/caracAL/node_modules/jsdom/lib/jsdom/browser/Window.js:521:9)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) ReferenceError: is_sdk is not defined
    at resolve_deferred (file://./game_files/752/common_functions.js:498:2)
    at resolve_deferreds (file://./game_files/752/common_functions.js:484:51)
    at smart.on_done (file://./game_files/752/runner_functions.js:1651:12)
    at smart_move_logic (file://./game_files/752/runner_functions.js:1871:10)
    at Window.<anonymous> (file://./game_files/752/runner_functions.js:1900:24)
    at Timeout.task [as _onTimeout] (/home/telokis/dev/git/caracAL/node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

Trigger from the following game code:

![image](https://user-images.githubusercontent.com/6382729/188990245-28e301fd-8848-4a68-ac01-513faf3a0a1e.png)

**Comment by Telokis** [comment]
Always happens right after a `smart_move` finishes. (At leat the path has been travelled. I guess the promise never resolves)

**Comment by numbereself** [comment]
Fixified as of 64cdf49
